# Generated by Django 3.0.8 on 2020-08-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='creative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='facebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='google',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='graphic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='influencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='sem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='seo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='socialmediamarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='webdesigning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para1', models.TextField()),
                ('para2', models.TextField()),
                ('img1', models.ImageField(upload_to='images')),
                ('img2', models.ImageField(upload_to='images')),
            ],
        ),
    ]
